const mongoose = require('mongoose');

const vendorGroupSchema = new mongoose.Schema({
  name: { type: String, required: true },
  nameAmharic: String,
  description: String,
  descriptionAmharic: String,
  
  // Group type
  groupType: {
    type: String,
    enum: ['manual', 'auto_location', 'auto_price', 'auto_category', 'auto_rating'],
    default: 'manual'
  },
  
  category: { 
    type: String, 
    enum: ['cooking', 'craft_making', 'textile_work', 'services', 'household', 'beauty', 'other'],
    required: true 
  },
  
  members: [{ type: mongoose.Schema.Types.ObjectId, ref: 'User' }],
  admin: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  
  // Location-based grouping
  location: {
    city: String,
    subcity: String,
    radius: { type: Number, default: 5 } // km radius for auto-grouping
  },
  
  // Price-based grouping
  priceRange: {
    min: { type: Number, default: 0 },
    max: { type: Number, default: 10000 },
    currency: { type: String, default: 'ETB' }
  },
  
  // Rating-based grouping
  ratingRange: {
    min: { type: Number, default: 0, min: 0, max: 5 },
    max: { type: Number, default: 5, min: 0, max: 5 }
  },
  
  // Group statistics
  stats: {
    totalMembers: { type: Number, default: 0 },
    averageRating: { type: Number, default: 0 },
    totalProducts: { type: Number, default: 0 },
    totalServices: { type: Number, default: 0 },
    priceRange: {
      min: Number,
      max: Number,
      average: Number
    }
  },
  
  isActive: { type: Boolean, default: true },
  isAutoGenerated: { type: Boolean, default: false }
  
}, { timestamps: true });

// Index for faster queries
vendorGroupSchema.index({ 'location.city': 1, 'location.subcity': 1 });
vendorGroupSchema.index({ category: 1 });
vendorGroupSchema.index({ groupType: 1 });
vendorGroupSchema.index({ 'priceRange.min': 1, 'priceRange.max': 1 });

module.exports = mongoose.model('VendorGroup', vendorGroupSchema);
