const VendorGroup = require('../models/VendorGroup');
const User = require('../models/User');
const Product = require('../models/Product');
const Service = require('../models/Service');

class AutoGroupingService {
  
  // Auto-group vendors by location
  async groupByLocation(city, subcity = null, category = null) {
    try {
      const filter = {
        role: 'vendor',
        'location.city': city
      };
      
      if (subcity) filter['location.subcity'] = subcity;
      
      const vendors = await User.find(filter);
      
      if (vendors.length < 2) {
        return null; // Need at least 2 vendors to create a group
      }
      
      // Check if group already exists
      const existingGroup = await VendorGroup.findOne({
        groupType: 'auto_location',
        'location.city': city,
        'location.subcity': subcity,
        category: category || 'other',
        isActive: true
      });
      
      if (existingGroup) {
        // Update existing group
        existingGroup.members = vendors.map(v => v._id);
        existingGroup.stats.totalMembers = vendors.length;
        await existingGroup.save();
        return existingGroup;
      }
      
      // Create new auto-generated group
      const groupName = subcity 
        ? `${subcity}, ${city} Vendors`
        : `${city} Vendors`;
      
      const group = await VendorGroup.create({
        name: groupName,
        nameAmharic: `የ${city} ሻጮች`,
        description: `Auto-generated group for vendors in ${subcity ? subcity + ', ' : ''}${city}`,
        groupType: 'auto_location',
        category: category || 'other',
        location: { city, subcity },
        members: vendors.map(v => v._id),
        admin: vendors[0]._id, // First vendor as admin
        isAutoGenerated: true,
        stats: {
          totalMembers: vendors.length
        }
      });
      
      await this.updateGroupStats(group._id);
      return group;
      
    } catch (error) {
      console.error('Auto-group by location error:', error);
      return null;
    }
  }
  
  // Auto-group vendors by price range
  async groupByPriceRange(minPrice, maxPrice, category = null) {
    try {
      // Find products/services in price range
      const productFilter = {
        price: { $gte: minPrice, $lte: maxPrice },
        isActive: true
      };
      
      if (category) productFilter.category = category;
      
      const [products, services] = await Promise.all([
        Product.find(productFilter).distinct('vendor'),
        Service.find(productFilter).distinct('provider')
      ]);
      
      const vendorIds = [...new Set([...products, ...services])];
      
      if (vendorIds.length < 2) {
        return null;
      }
      
      // Check if group exists
      const existingGroup = await VendorGroup.findOne({
        groupType: 'auto_price',
        'priceRange.min': minPrice,
        'priceRange.max': maxPrice,
        category: category || 'other',
        isActive: true
      });
      
      if (existingGroup) {
        existingGroup.members = vendorIds;
        existingGroup.stats.totalMembers = vendorIds.length;
        await existingGroup.save();
        return existingGroup;
      }
      
      // Create new price-based group
      const groupName = `${minPrice}-${maxPrice} ETB Vendors`;
      
      const group = await VendorGroup.create({
        name: groupName,
        nameAmharic: `${minPrice}-${maxPrice} ብር ሻጮች`,
        description: `Auto-generated group for vendors with products/services priced between ${minPrice} and ${maxPrice} ETB`,
        groupType: 'auto_price',
        category: category || 'other',
        priceRange: { min: minPrice, max: maxPrice },
        members: vendorIds,
        admin: vendorIds[0],
        isAutoGenerated: true,
        stats: {
          totalMembers: vendorIds.length
        }
      });
      
      await this.updateGroupStats(group._id);
      return group;
      
    } catch (error) {
      console.error('Auto-group by price error:', error);
      return null;
    }
  }
  
  // Auto-group vendors by category
  async groupByCategory(category) {
    try {
      // Find vendors with products/services in this category
      const [products, services] = await Promise.all([
        Product.find({ category, isActive: true }).distinct('vendor'),
        Service.find({ category, isActive: true }).distinct('provider')
      ]);
      
      const vendorIds = [...new Set([...products, ...services])];
      
      if (vendorIds.length < 2) {
        return null;
      }
      
      // Check if group exists
      const existingGroup = await VendorGroup.findOne({
        groupType: 'auto_category',
        category,
        isActive: true
      });
      
      if (existingGroup) {
        existingGroup.members = vendorIds;
        existingGroup.stats.totalMembers = vendorIds.length;
        await existingGroup.save();
        return existingGroup;
      }
      
      // Create category-based group
      const groupName = `${category.replace(/_/g, ' ').toUpperCase()} Vendors`;
      
      const group = await VendorGroup.create({
        name: groupName,
        description: `Auto-generated group for ${category} vendors`,
        groupType: 'auto_category',
        category,
        members: vendorIds,
        admin: vendorIds[0],
        isAutoGenerated: true,
        stats: {
          totalMembers: vendorIds.length
        }
      });
      
      await this.updateGroupStats(group._id);
      return group;
      
    } catch (error) {
      console.error('Auto-group by category error:', error);
      return null;
    }
  }
  
  // Auto-group vendors by rating
  async groupByRating(minRating, maxRating = 5, category = null) {
    try {
      // Find vendors with ratings in range
      const filter = {
        role: 'vendor',
        rating: { $gte: minRating, $lte: maxRating }
      };
      
      const vendors = await User.find(filter);
      
      if (vendors.length < 2) {
        return null;
      }
      
      // Filter by category if specified
      let vendorIds = vendors.map(v => v._id);
      
      if (category) {
        const [products, services] = await Promise.all([
          Product.find({ 
            vendor: { $in: vendorIds }, 
            category, 
            isActive: true 
          }).distinct('vendor'),
          Service.find({ 
            provider: { $in: vendorIds }, 
            category, 
            isActive: true 
          }).distinct('provider')
        ]);
        
        vendorIds = [...new Set([...products, ...services])];
        
        if (vendorIds.length < 2) {
          return null;
        }
      }
      
      // Check if group exists
      const existingGroup = await VendorGroup.findOne({
        groupType: 'auto_rating',
        'ratingRange.min': minRating,
        'ratingRange.max': maxRating,
        category: category || 'other',
        isActive: true
      });
      
      if (existingGroup) {
        existingGroup.members = vendorIds;
        existingGroup.stats.totalMembers = vendorIds.length;
        await existingGroup.save();
        return existingGroup;
      }
      
      // Create rating-based group
      let groupName;
      if (minRating >= 4.5) {
        groupName = `Top Rated Vendors (${minRating}+ ⭐)`;
      } else if (minRating >= 4.0) {
        groupName = `Highly Rated Vendors (${minRating}+ ⭐)`;
      } else if (minRating >= 3.5) {
        groupName = `Good Rated Vendors (${minRating}+ ⭐)`;
      } else {
        groupName = `${minRating}-${maxRating} ⭐ Vendors`;
      }
      
      const group = await VendorGroup.create({
        name: groupName,
        nameAmharic: `${minRating}+ ⭐ ሻጮች`,
        description: `Auto-generated group for vendors with ${minRating}-${maxRating} star ratings`,
        groupType: 'auto_rating',
        category: category || 'other',
        ratingRange: { min: minRating, max: maxRating },
        members: vendorIds,
        admin: vendorIds[0],
        isAutoGenerated: true,
        stats: {
          totalMembers: vendorIds.length
        }
      });
      
      await this.updateGroupStats(group._id);
      return group;
      
    } catch (error) {
      console.error('Auto-group by rating error:', error);
      return null;
    }
  }
  
  // Update group statistics
  async updateGroupStats(groupId) {
    try {
      const group = await VendorGroup.findById(groupId).populate('members');
      
      if (!group) return;
      
      // Get all products and services from group members
      const memberIds = group.members.map(m => m._id);
      
      const [products, services, vendors] = await Promise.all([
        Product.find({ vendor: { $in: memberIds }, isActive: true }),
        Service.find({ provider: { $in: memberIds }, isActive: true }),
        User.find({ _id: { $in: memberIds } })
      ]);
      
      // Calculate statistics
      const allItems = [...products, ...services];
      const prices = allItems.map(item => item.price).filter(p => p > 0);
      const ratings = vendors.map(v => v.rating || 0).filter(r => r > 0);
      
      group.stats = {
        totalMembers: group.members.length,
        averageRating: ratings.length > 0 
          ? (ratings.reduce((a, b) => a + b, 0) / ratings.length).toFixed(1)
          : 0,
        totalProducts: products.length,
        totalServices: services.length,
        priceRange: {
          min: prices.length > 0 ? Math.min(...prices) : 0,
          max: prices.length > 0 ? Math.max(...prices) : 0,
          average: prices.length > 0 
            ? Math.round(prices.reduce((a, b) => a + b, 0) / prices.length)
            : 0
        }
      };
      
      await group.save();
      return group;
      
    } catch (error) {
      console.error('Update group stats error:', error);
      return null;
    }
  }
  
  // Generate all auto-groups for a city
  async generateCityGroups(city) {
    try {
      const results = {
        location: [],
        price: [],
        category: [],
        rating: []
      };
      
      // Get all subcities in this city
      const subcities = await User.distinct('location.subcity', {
        'location.city': city,
        role: 'vendor'
      });
      
      // Create location-based groups for each subcity
      for (const subcity of subcities) {
        if (subcity) {
          const group = await this.groupByLocation(city, subcity);
          if (group) results.location.push(group);
        }
      }
      
      // Create price-based groups
      const priceRanges = [
        { min: 0, max: 100 },
        { min: 100, max: 500 },
        { min: 500, max: 1000 },
        { min: 1000, max: 5000 },
        { min: 5000, max: 10000 }
      ];
      
      for (const range of priceRanges) {
        const group = await this.groupByPriceRange(range.min, range.max);
        if (group) results.price.push(group);
      }
      
      // Create category-based groups
      const categories = ['cooking', 'craft_making', 'textile_work', 'services', 'household', 'beauty'];
      
      for (const category of categories) {
        const group = await this.groupByCategory(category);
        if (group) results.category.push(group);
      }
      
      // Create rating-based groups
      const ratingRanges = [
        { min: 4.5, max: 5, name: 'Top Rated' },
        { min: 4.0, max: 4.9, name: 'Highly Rated' },
        { min: 3.5, max: 3.9, name: 'Good Rated' },
        { min: 3.0, max: 3.4, name: 'Average Rated' }
      ];
      
      for (const range of ratingRanges) {
        const group = await this.groupByRating(range.min, range.max);
        if (group) results.rating.push(group);
      }
      
      return results;
      
    } catch (error) {
      console.error('Generate city groups error:', error);
      return null;
    }
  }
  
  // Find suggested groups for a vendor
  async suggestGroupsForVendor(vendorId) {
    try {
      const vendor = await User.findById(vendorId);
      
      if (!vendor || vendor.role !== 'vendor') {
        return [];
      }
      
      const suggestions = [];
      
      // Get vendor's products and services
      const [products, services] = await Promise.all([
        Product.find({ vendor: vendorId, isActive: true }),
        Service.find({ provider: vendorId, isActive: true })
      ]);
      
      // Suggest location-based groups
      if (vendor.location?.city) {
        const locationGroups = await VendorGroup.find({
          groupType: 'auto_location',
          'location.city': vendor.location.city,
          members: { $ne: vendorId },
          isActive: true
        }).limit(2);
        
        suggestions.push(...locationGroups);
      }
      
      // Suggest price-based groups
      const allItems = [...products, ...services];
      if (allItems.length > 0) {
        const avgPrice = allItems.reduce((sum, item) => sum + item.price, 0) / allItems.length;
        
        const priceGroups = await VendorGroup.find({
          groupType: 'auto_price',
          'priceRange.min': { $lte: avgPrice },
          'priceRange.max': { $gte: avgPrice },
          members: { $ne: vendorId },
          isActive: true
        }).limit(2);
        
        suggestions.push(...priceGroups);
      }
      
      // Suggest category-based groups
      const categories = [...new Set([
        ...products.map(p => p.category),
        ...services.map(s => s.category)
      ])];
      
      for (const category of categories) {
        const categoryGroups = await VendorGroup.find({
          groupType: 'auto_category',
          category,
          members: { $ne: vendorId },
          isActive: true
        }).limit(1);
        
        suggestions.push(...categoryGroups);
      }
      
      // Suggest rating-based groups
      if (vendor.rating && vendor.rating > 0) {
        const ratingGroups = await VendorGroup.find({
          groupType: 'auto_rating',
          'ratingRange.min': { $lte: vendor.rating },
          'ratingRange.max': { $gte: vendor.rating },
          members: { $ne: vendorId },
          isActive: true
        }).limit(2);
        
        suggestions.push(...ratingGroups);
      }
      
      return suggestions;
      
    } catch (error) {
      console.error('Suggest groups error:', error);
      return [];
    }
  }
}

module.exports = new AutoGroupingService();
